# Generated by Django 5.2 on 2025-05-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='player_photo/%y/%m/%d', verbose_name='Фото')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=255, verbose_name='Национальность')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.position', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Футболист',
                'verbose_name_plural': 'Состав команды',
            },
        ),
    ]
