# Generated by Django 5.2 on 2025-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=255, verbose_name='Противник')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='team_photo/%y/%m/%d', verbose_name='Лого')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='Счёт')),
                ('is_home', models.BooleanField(choices=[(False, 'гостевая игра'), (True, 'домашняя игра')], default=1, verbose_name='Расположение')),
                ('is_future', models.BooleanField(choices=[(False, 'не сыгранна'), (True, 'сыгранна')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
